/**
 * Last generated by Orchestration Designer at: 2023-NOV-20  03:50:29 PM
 */
package english.prompts;


import com.avaya.sce.runtime.Prompt;
import com.avaya.sce.runtime.PromptElement;
import com.avaya.sce.runtimecommon.SCESession;



import flow.KeyData;

public class PromptForValid extends com.avaya.sce.runtime.Prompt {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for PromptForValid.
	 */
	public PromptForValid() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}


	@Override
	public void updatePrompt(SCESession mySession ) {		
			
		String audioUrl = mySession.getServlet().getServletContext().getInitParameter("Test");
		String menuPrompt = KeyData.oProp.getProperty("testPrompt");
		String[] mp = menuPrompt.split(",");
		  
		for(int i =0;i<mp.length;i++) {	
			
			String prompt1 = mp[i];
			

//			String fullAudioUrl = audioUrl+prompt+".wav";
//		    add(1, new PromptElement(com.avaya.sce.runtime.PromptElement.TEXT, fullAudioUrl, false));
		   
			
		    mySession.getVariableField("prompt", "pm" + i).setValue(audioUrl + prompt1 + ".wav");
			
//		    String getprompt = mySession
//					.getVariableField("prompt", "pm" + i)
//					.getStringValue();

		    System.out.println("============proompts===============" + prompt1);

			add(1, new com.avaya.sce.runtime.PhraseVariableElement("prompt:pm" + i,
					com.avaya.sce.runtime.PhraseVariableElement.Type.AUDIO_URL, false));
		    
		}			
			
	}


	/**
	 * This method is generated automatically and should not be manually edited
	 * To manually edit the prompt, override:
	 * void updatePrompt()
	 * Last generated by Orchestration Designer at: 2023-NOV-24  07:02:24 PM
	 */
	public void buildPrompt(){
		com.avaya.sce.runtime.Format format = null;
		com.avaya.sce.runtime.RenderHint hint = null;
		com.avaya.sce.runtime.MediaPage mediaPage = null;
		setBarginType(com.avaya.sce.runtimecommon.SCERT.BARGIN_SPEECH);
		setName("PromptForValid");
		setOrder(com.avaya.sce.runtime.Prompt.STANDARD);

		// Prompt level 1
		setTimeout(1,8000);
		setBargin(1,true);

		add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.PHRASESET,"TTOutbound1:ETOUTBOUND_008",false));

		format = new com.avaya.sce.runtime.Format();
		format.add("gender","male");
		format.add("age","30");
		add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.XML_TAG_BEGIN,"voice", format));
			format = new com.avaya.sce.runtime.Format();
			format.add(com.avaya.sce.runtime.Format.FORMAT,com.avaya.sce.runtime.Format.FMT_DIGITS);
			add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.VARIABLE_TEXT,"CustomTTNum", format));
		add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.XML_TAG_END,"voice"));

		add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.PHRASESET,"TTOutbound1:ETOUTBOUND_009",false));

		add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.PHRASESET,"TTOutbound1:ETOUTBOUND_010",false));

		add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.PHRASESET,"TTOutbound1:ETOUTBOUND_001",false));

		add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.PHRASESET,"TTOutbound1:ETOUTBOUND_011",false));

		add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.PHRASESET,"TTOutbound1:ETOUTBOUND_002",false));

		add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.PHRASESET,"TTOutbound1:ETOUTBOUND_012",false));

		add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.PHRASESET,"TTOutbound1:ETOUTBOUND_003",false));

		add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.PHRASESET,"TTOutbound1:ETOUTBOUND_013",false));

		add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.PHRASESET,"TTOutbound1:ETOUTBOUND_004",false));

		add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.PHRASESET,"TTOutbound1:ETOUTBOUND_014",false));

		add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.PHRASESET,"TTOutbound1:ETOUTBOUND_006",false));

		add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.PHRASESET,"TTOutbound1:ETOUTBOUND_007",false));

	}
	
	
}
