/**
 * Last generated by Orchestration Designer at: 2023-NOV-28  02:51:55 PM
 */
package english.prompts;

import com.avaya.sce.runtime.PhraseVariableElement;
import com.avaya.sce.runtimecommon.SCESession;

import flow.IProjectVariables;

public class DynamicPrompt1 extends com.avaya.sce.runtime.Prompt {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for DynamicPrompt1.
	 */
	public DynamicPrompt1() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}


	


	/**
	 * This method is generated automatically and should not be manually edited
	 * To manually edit the prompt, override:
	 * void updatePrompt()
	 * Last generated by Orchestration Designer at: 2023-DEC-01  10:46:15 AM
	 */
	public void buildPrompt(){
		com.avaya.sce.runtime.Format format = null;
		com.avaya.sce.runtime.RenderHint hint = null;
		com.avaya.sce.runtime.MediaPage mediaPage = null;
		setBarginType(com.avaya.sce.runtimecommon.SCERT.BARGIN_SPEECH);
		setName("DynamicPrompt1");
		setOrder(com.avaya.sce.runtime.Prompt.STANDARD);

		// Prompt level 1
		setTimeout(1,8000);
		setBargin(1,true);

	}
	
	@Override
	public void updatePrompt(SCESession mySession) {
		
		String audioUrlPath = mySession.getServlet().getServletContext().getInitParameter("AvAudio");
		
		String promptArray = mySession.getVariableField(IProjectVariables.USER_STORE,IProjectVariables.USER_STORE_FIELD_PROMPT).getStringValue();
		String grammarArray = mySession.getVariableField(IProjectVariables.USER_STORE,IProjectVariables.USER_STORE_FIELD_GRAMMAR).getStringValue();
		
		System.out.println("=========audioUrlPath======="+audioUrlPath);
		System.out.println("=========promptArray======="+promptArray);
		System.out.println("=========grammarArray======="+grammarArray);
		
		String[] prompts = promptArray.split(",");
		String[] grammars = grammarArray.split(",");
		
		String grammarValue=null;
		String promptValue =null;
		
		for(int i = 0;i<grammars.length;i++) {
			
			String prom = prompts[i];
			String gram = grammars[i];
			
			System.out.println("=========prom======="+prom);
			System.out.println("=========gram======="+gram);
			
			mySession.getVariableField("Press", "press" + gram).setValue(audioUrlPath+"press" + gram + ".wav");
		    grammarValue = mySession.getVariableField("Press", "press" + gram).getStringValue();
			System.out.println("=========grammarValue======="+grammarValue);
			
			mySession.getVariableField("prompt", "pm" + i).setValue(audioUrlPath + prom + ".wav");
			promptValue = mySession.getVariableField("prompt", "pm" + i).getStringValue();
			System.out.println("=========promptValue======="+promptValue);
			
			add(1,new com.avaya.sce.runtime.PhraseVariableElement("Press:press" + gram, com.avaya.sce.runtime.PhraseVariableElement.Type.AUDIO_URL, false));
			add(1,new com.avaya.sce.runtime.PhraseVariableElement("prompt:pm" + i, com.avaya.sce.runtime.PhraseVariableElement.Type.AUDIO_URL, false));
		}
		
		System.out.println("=========grammarValue1======="+grammarValue);
		System.out.println("=========promptValue1======="+promptValue);
		
	}
}
