/**
 * Last generated by Orchestration Designer at: 2023-NOV-28  06:31:46 PM
 */
package english.prompts;

import com.avaya.sce.runtime.PhraseVariableElement;
import com.avaya.sce.runtimecommon.SCESession;

import flow.IProjectVariables;

public class OtherPrompt extends com.avaya.sce.runtime.Prompt {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for OtherPrompt.
	 */
	public OtherPrompt() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}


	/**
	 * This method is generated automatically and should not be manually edited
	 * To manually edit the prompt, override:
	 * void updatePrompt()
	 * Last generated by Orchestration Designer at: 2023-DEC-01  10:46:16 AM
	 */
	public void buildPrompt(){
		com.avaya.sce.runtime.Format format = null;
		com.avaya.sce.runtime.RenderHint hint = null;
		com.avaya.sce.runtime.MediaPage mediaPage = null;
		setBarginType(com.avaya.sce.runtimecommon.SCERT.BARGIN_SPEECH);
		setName("OtherPrompt");
		setOrder(com.avaya.sce.runtime.Prompt.STANDARD);

		// Prompt level 1
		setTimeout(1,8000);
		setBargin(1,true);

	}


	@Override
	public void updatePrompt(SCESession mySession) {
		
		String audioUrl = mySession.getServlet().getServletContext().getInitParameter("AvAudio");
		
		String[] prompts = mySession.getVariableField(IProjectVariables.USER_STORE, IProjectVariables.USER_STORE_FIELD_PROMPT).getStringValue().split(",");
		
		for(int i = 0; i<prompts.length;i++) {
			
			String pm = prompts[i];
			
			mySession.getVariableField("prompt", "pm").setValue(audioUrl+pm+".wav");
			
			add(1,new PhraseVariableElement("prompt:pm",PhraseVariableElement.Type.AUDIO_URL,false));
			
		}
		
		
	}
	
	
}
