/**
 * Last generated by Orchestration Designer at: 2023-NOV-28  12:16:36 PM
 */
package english.prompts;

import com.avaya.sce.runtime.PromptElement;
import com.avaya.sce.runtimecommon.SCESession;

public class WelcomeP extends com.avaya.sce.runtime.Prompt {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for WelcomeP.
	 */
	public WelcomeP() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}


	@Override
	public void updatePrompt(SCESession mySession) {
		
		String audioUrlPath = mySession.getServlet().getServletContext().getInitParameter("AvAudio");
		
		mySession.getVariableField("prompt","Welcome").setValue(audioUrlPath+"Welcome"+".wav");
		
		add(1, new com.avaya.sce.runtime.PhraseVariableElement("prompt:Welcome",com.avaya.sce.runtime.PhraseVariableElement.Type.AUDIO_URL, false));
		
	}


	/**
	 * This method is generated automatically and should not be manually edited
	 * To manually edit the prompt, override:
	 * void updatePrompt()
	 * Last generated by Orchestration Designer at: 2023-DEC-01  10:46:16 AM
	 */
	public void buildPrompt(){
		com.avaya.sce.runtime.Format format = null;
		com.avaya.sce.runtime.RenderHint hint = null;
		com.avaya.sce.runtime.MediaPage mediaPage = null;
		setBarginType(com.avaya.sce.runtimecommon.SCERT.BARGIN_SPEECH);
		setName("WelcomeP");
		setOrder(com.avaya.sce.runtime.Prompt.STANDARD);

		// Prompt level 1
		setTimeout(1,8000);
		setBargin(1,true);

	}
}
