package english.phrasesets;

/**
 * This phraseset class will be automatically populated with data from the 
 * phraseset project file.  Manual edits should only be outside of the tag 
 * areas or overridden methods. 
 * Class created on: 
 * Last generated by Orchestration Designer at: 2023-DEC-27  02:49:44 PM
 */
public class PhraseSet1 extends com.avaya.sce.runtime.Phraseset { 

	//{{START:CLASS:FIELDS
	private static final com.avaya.sce.runtime.Phraseset.PhraseMap PHRASE_MAP;
	//}}END:CLASS:FIELDS

	/**
	 * Static initializer
	 */
	static {
		//{{START:PHRASESET:STATIC

		// Create the phrase map, then populate with phrases
		PHRASE_MAP = new com.avaya.sce.runtime.Phraseset.PhraseMap(80);
		com.avaya.sce.runtime.Phrase phrase;

		// phrase: Welcome
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.PhraseSet1.urlbase", "Welcome", "Welcome.wav", ""); 

		// phrase: AT
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.PhraseSet1.urlbase", "AT", "AT.wav", ""); 

		// phrase: ChangeAtmPin
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.PhraseSet1.urlbase", "ChangeAtmPin", "ChangeAtmPin.wav", ""); 

		// phrase: CheckBalance
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.PhraseSet1.urlbase", "CheckBalance", "CheckBalance.wav", ""); 

		// phrase: ListenAgain
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.PhraseSet1.urlbase", "ListenAgain", "ListenAgain.wav", ""); 

		// phrase: NINM_MAXTRY
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.PhraseSet1.urlbase", "NINM_MAXTRY", "NINM_MAXTRY.wav", ""); 

		// phrase: NINM_NOINPUT
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.PhraseSet1.urlbase", "NINM_NOINPUT", "NINM_NOINPUT.wav", ""); 

		// phrase: NINM_NOMATCH
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.PhraseSet1.urlbase", "NINM_NOMATCH", "NINM_NOMATCH.wav", ""); 

		// phrase: Press
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.PhraseSet1.urlbase", "Press", "Press.wav", ""); 

		// phrase: press0
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.PhraseSet1.urlbase", "press0", "press0.wav", ""); 

		// phrase: press1
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.PhraseSet1.urlbase", "press1", "press1.wav", ""); 

		// phrase: press2
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.PhraseSet1.urlbase", "press2", "press2.wav", ""); 

		// phrase: press3
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.PhraseSet1.urlbase", "press3", "press3.wav", ""); 

		// phrase: press4
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.PhraseSet1.urlbase", "press4", "press4.wav", ""); 

		// phrase: press9
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.PhraseSet1.urlbase", "press9", "press9.wav", ""); 

		// phrase: press5
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.PhraseSet1.urlbase", "press5", "press5.wav", ""); 

		// phrase: press6
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.PhraseSet1.urlbase", "press6", "press6.wav", ""); 

		// phrase: press7
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.PhraseSet1.urlbase", "press7", "press7.wav", ""); 

		// phrase: press8
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.PhraseSet1.urlbase", "press8", "press8.wav", ""); 

		// phrase: pressStar
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.PhraseSet1.urlbase", "pressStar", "pressStar.wav", ""); 

		// phrase: Hindi
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.PhraseSet1.urlbase", "Hindi", "Hindi.wav", ""); 

		// phrase: English
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.PhraseSet1.urlbase", "English", "English.wav", ""); 

		// phrase: Tamil
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.PhraseSet1.urlbase", "Tamil", "Tamil.wav", ""); 

		// phrase: pressHash
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.PhraseSet1.urlbase", "pressHash", "pressHash.wav", ""); 

		// phrase: Exit
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.PhraseSet1.urlbase", "Exit", "Exit.wav", ""); 

		// phrase: Thank
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.PhraseSet1.urlbase", "Thank", "Thank.wav", ""); 

		// phrase: TryAgain
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.PhraseSet1.urlbase", "TryAgain", "TryAgain.wav", ""); 

		// phrase: Otp
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.PhraseSet1.urlbase", "Otp", "Otp.wav", ""); 

		// phrase: ResendOtp
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.PhraseSet1.urlbase", "ResendOtp", "ResendOtp.wav", ""); 

		// phrase: EntAccountNum
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.PhraseSet1.urlbase", "EntAccountNum", "EntAccountNum.wav", ""); 

		// phrase: EntCustomerId
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.PhraseSet1.urlbase", "EntCustomerId", "EntCustomerId.wav", ""); 

		// phrase: AccountBal
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.PhraseSet1.urlbase", "AccountBal", "AccountBal.wav", ""); 

		// phrase: AT1
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.PhraseSet1.urlbase", "AT1", "AT1.wav", ""); 

		// phrase: CardNum
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.PhraseSet1.urlbase", "CardNum", "CardNum.wav", ""); 

		// phrase: Cvv
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.PhraseSet1.urlbase", "Cvv", "Cvv.wav", ""); 

		// phrase: NewPin
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.PhraseSet1.urlbase", "NewPin", "NewPin.wav", ""); 

		// phrase: ConfirmPinNum
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.PhraseSet1.urlbase", "ConfirmPinNum", "ConfirmPinNum.wav", ""); 

		// phrase: PinChangedS
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.PhraseSet1.urlbase", "PinChangedS", "PinChangedS.wav", ""); 

		// phrase: ChangeLang
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.PhraseSet1.urlbase", "ChangeLang", "ChangeLang.wav", ""); 

		// phrase: PinNotMatching
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.PhraseSet1.urlbase", "PinNotMatching", "PinNotMatching.wav", ""); 

		//}}END:PHRASESET:STATIC
	}
	/**
	 * Returns the Phrase with the given name.  To override the
	 * behavior and dynamically return a different Phrase object,
	 * override the method "hookGetPhrase(...)".
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2024-FEB-08  04:57:46 PM
	 * @see com.avaya.sce.runtime.Phraseset#getPhrase(String) 
	 */ 
	public com.avaya.sce.runtime.Phrase getPhrase(String phraseName) {
		return(getPhrase(PhraseSet1.PHRASE_MAP, phraseName));
	}
}
