package connectivity.ws.operations;

/**
 * This class is generated automatically.  Manual edits must be outside of the tagged
 * areas (for example, "START:CLASS:..." and "END:CLASS:...").  Changes within the
 * tag areas will be overwritten when the web service operation is regenerated.
 * Last generated by Orchestration Designer at: 2023-NOV-20  02:34:59 PM
 */
public class WS1 extends com.avaya.sce.runtime.connectivity.restws.CallService {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

    /**
    * Constructor for WS1.
    */
    public WS1( com.avaya.sce.runtimecommon.IRuntimeSession mySession ) {
		//{{START:CLASS:CONSTRUCTOR
        super(mySession);

        //Web Service
        setServiceName("WS1");
		setHttpMethod("GET");
		setOutputFormat("Server Default");
		setUseQuery("false");
		setUseJavaObject("true");
		setUseBody("false");
        setTimeoutSecondsFromParameter("WS1_1700471097340TimeoutSeconds");
        setEndpointFromParameter("WS1_1700471097340EndpointUrl");
        setAuthenticationFromParameter("WS1_1700471097340Authentication");
        setPasswordFromParameter("WS1_1700471097340Password");
        setUsernameFromParameter("WS1_1700471097341Username");
        setPreemptiveFromParameter("WS1_1700471097341Preemptive");
        setSecurityFromParameter("WS1_1700471097341Security");
        setPortFromParameter("WS1_1700471097341Port");

        //Operation
        setOperation(new javax.xml.namespace.QName("", "WS1_OP"));

        //Input parameters

        //Output parameters
        {
            com.avaya.sce.runtime.connectivity.restws.WsParam param1 = new com.avaya.sce.runtime.connectivity.restws.WsParam(new javax.xml.namespace.QName("Id"));
            param1.setWrapped(false);
            param1.setParamType(0);
            param1.setDDVariableName("WS1Variables:Id");
            addOutParameter(param1);
        }
        {
            com.avaya.sce.runtime.connectivity.restws.WsParam param1 = new com.avaya.sce.runtime.connectivity.restws.WsParam(new javax.xml.namespace.QName("login"));
            param1.setWrapped(false);
            param1.setParamType(0);
            param1.setDDVariableName("WS1Variables:login");
            addOutParameter(param1);
        }
        {
            com.avaya.sce.runtime.connectivity.restws.WsParam param1 = new com.avaya.sce.runtime.connectivity.restws.WsParam(new javax.xml.namespace.QName("name"));
            param1.setWrapped(false);
            param1.setParamType(0);
            param1.setDDVariableName("WS1Variables:name");
            addOutParameter(param1);
        }
		setMessageBody("");
        //}}END:CLASS:CONSTRUCTOR






























    }

}

