<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<RestWebServiceOperation version="1.0">
    <Name>WS1</Name>
    <ServerUrl>https://api.github.com/users/mojombo</ServerUrl>
    <EndpointVariable/>
    <HttpMethod>GET</HttpMethod>
    <UseQuery>false</UseQuery>
    <OutputFormat>Server Default</OutputFormat>
    <UseJavaObject>true</UseJavaObject>
    <UseBody>false</UseBody>
    <Operation>
        <Name>WS1_OP</Name>
        <Inparams/>
        <Outprarms>
            <Outparam>
                <Name>Id</Name>
                <VariableName>WS1Variables:Id</VariableName>
                <IsWrapper>false</IsWrapper>
                <ShowUnwrapped>false</ShowUnwrapped>
                <ParamType>0</ParamType>
            </Outparam>
            <Outparam>
                <Name>login</Name>
                <VariableName>WS1Variables:login</VariableName>
                <IsWrapper>false</IsWrapper>
                <ShowUnwrapped>false</ShowUnwrapped>
                <ParamType>0</ParamType>
            </Outparam>
            <Outparam>
                <Name>name</Name>
                <VariableName>WS1Variables:name</VariableName>
                <IsWrapper>false</IsWrapper>
                <ShowUnwrapped>false</ShowUnwrapped>
                <ParamType>0</ParamType>
            </Outparam>
        </Outprarms>
        <Headers/>
    </Operation>
    <WebConfigParameterNames>
        <TimeoutSeconds>WS1_1700471097340TimeoutSeconds</TimeoutSeconds>
        <EndpointUrl>WS1_1700471097340EndpointUrl</EndpointUrl>
        <Authentication>WS1_1700471097340Authentication</Authentication>
        <Password>WS1_1700471097340Password</Password>
        <Username>WS1_1700471097341Username</Username>
        <Preemptive>WS1_1700471097341Preemptive</Preemptive>
        <Security>WS1_1700471097341Security</Security>
        <Port>WS1_1700471097341Port</Port>
    </WebConfigParameterNames>
    <MessageBody/>
    <Keystore/>
    <KeystorePassword/>
</RestWebServiceOperation>
