/**
 * Last generated by Orchestration Designer at: 2024-JAN-08  01:27:42 PM
 */
package english.prompts;

import com.avaya.sce.runtimecommon.SCESession;

import flow.IProjectVariables;

public class DyExceededPrompt extends com.avaya.sce.runtime.Prompt {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for DyExceededPrompt.
	 */
	public DyExceededPrompt() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}


	/**
	 * This method is generated automatically and should not be manually edited
	 * To manually edit the prompt, override:
	 * void updatePrompt()
	 * Last generated by Orchestration Designer at: 2024-FEB-08  12:15:31 PM
	 */
	public void buildPrompt(){
		com.avaya.sce.runtime.Format format = null;
		com.avaya.sce.runtime.RenderHint hint = null;
		com.avaya.sce.runtime.MediaPage mediaPage = null;
		setBarginType(com.avaya.sce.runtimecommon.SCERT.BARGIN_SPEECH);
		setName("DyExceededPrompt");
		setOrder(com.avaya.sce.runtime.Prompt.STANDARD);

		// Prompt level 1
		setTimeout(1,8000);
		setBargin(1,true);

	}


	@Override
	public void updatePrompt(SCESession mySession) {
		
       String audioUrlPath = mySession.getServlet().getServletContext().getInitParameter("PromptFile");
		
		String maxTryPrompt = mySession.getVariableField(IProjectVariables.USER_STORE,IProjectVariables.USER_STORE_FIELD_MAX_TRIES).getStringValue();
		
		
		mySession.getVariableField("prompt", "pm" ).setValue(audioUrlPath + maxTryPrompt + ".wav");
		
		add(1,new com.avaya.sce.runtime.PhraseVariableElement("prompt:pm", com.avaya.sce.runtime.PhraseVariableElement.Type.AUDIO_URL, false));
		
	}
	
	
}
