/**
 * Last generated by Orchestration Designer at: 2024-JAN-06  11:44:33 AM
 */
package english.prompts;

import com.avaya.sce.runtimecommon.SCESession;

import flow.IProjectVariables;

public class EntCustIdPrompt extends com.avaya.sce.runtime.Prompt {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for EntCustIdPrompt.
	 */
	public EntCustIdPrompt() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}


	/**
	 * This method is generated automatically and should not be manually edited
	 * To manually edit the prompt, override:
	 * void updatePrompt()
	 * Last generated by Orchestration Designer at: 2024-FEB-08  11:01:17 AM
	 */
	public void buildPrompt(){
		com.avaya.sce.runtime.Format format = null;
		com.avaya.sce.runtime.RenderHint hint = null;
		com.avaya.sce.runtime.MediaPage mediaPage = null;
		setBarginType(com.avaya.sce.runtimecommon.SCERT.BARGIN_SPEECH);
		setName("EntCustIdPrompt");
		setOrder(com.avaya.sce.runtime.Prompt.STANDARD);

		// Prompt level 1
		setTimeout(1,8000);
		setBargin(1,true);

	}


	@Override
	public void updatePrompt(SCESession mySession) {
	String audioUrlPath = mySession.getServlet().getServletContext().getInitParameter("PromptFile");
		
		String promptArray = mySession.getVariableField(IProjectVariables.USER_STORE,IProjectVariables.USER_STORE_FIELD_PROMPT).getStringValue();
		
		String[] prompts = promptArray.split(",");
		
		String promptValue =null;
		
		for(int i = 0;i<prompts.length;i++) {
			
			String prom = prompts[i];			
			
			System.out.println("=========prom======="+prom);
			
			mySession.getVariableField("prompt", "pm" + i).setValue(audioUrlPath + prom + ".wav");
			promptValue = mySession.getVariableField("prompt", "pm" + i).getStringValue();
			System.out.println("=========promptValue======="+promptValue);
			
			add(1,new com.avaya.sce.runtime.PhraseVariableElement("prompt:pm" + i, com.avaya.sce.runtime.PhraseVariableElement.Type.AUDIO_URL, false));
		}
	}
	
	
	
}
