/**
 * Last generated by Orchestration Designer at: 2024-JAN-05  06:05:46 PM
 */
package english.prompts;

import com.avaya.sce.runtimecommon.SCESession;

import flow.IProjectVariables;

public class LangMenuPrompt extends com.avaya.sce.runtime.Prompt {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for LangMenuPrompt.
	 */
	public LangMenuPrompt() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}


	/**
	 * This method is generated automatically and should not be manually edited
	 * To manually edit the prompt, override:
	 * void updatePrompt()
	 * Last generated by Orchestration Designer at: 2024-FEB-08  11:01:17 AM
	 */
	public void buildPrompt(){
		com.avaya.sce.runtime.Format format = null;
		com.avaya.sce.runtime.RenderHint hint = null;
		com.avaya.sce.runtime.MediaPage mediaPage = null;
		setBarginType(com.avaya.sce.runtimecommon.SCERT.BARGIN_SPEECH);
		setName("LangMenuPrompt");
		setOrder(com.avaya.sce.runtime.Prompt.STANDARD);

		// Prompt level 1
		setTimeout(1,8000);
		setBargin(1,true);

	}


	@Override
	public void updatePrompt(SCESession mySession) {
		
       String audioUrl = mySession.getServlet().getServletContext().getInitParameter("PromptFile");
		
		String[] promptArray = mySession.getVariableField(IProjectVariables.USER_STORE,IProjectVariables.USER_STORE_FIELD_PROMPT).getStringValue().split(",");
		String[] grammarArray = mySession.getVariableField(IProjectVariables.USER_STORE,IProjectVariables.USER_STORE_FIELD_GRAMMAR).getStringValue().split(",");
		
         
		
		for(int i=0;i<grammarArray.length;i++) {
			
			String prom = promptArray[i];
			String gram = grammarArray[i];
			
			if(gram.equals("*")) {
				gram = "Star";
			}
			else if(gram.equals("#"))
			{
				gram = "Hash";
			}
			
            System.out.println("=========prom======="+prom);
            
            mySession.getVariableField("Press", "press" + i).setValue(audioUrl + "press" + gram + ".wav");
			String grammarValue = mySession.getVariableField("Press", "press" + i).getStringValue();
			System.out.println("=========promptValue======="+grammarValue);
			
			mySession.getVariableField("Prompt", "pm" + i).setValue(audioUrl + prom + ".wav");
			String promptValue = mySession.getVariableField("prompt", "pm" + i).getStringValue();
			System.out.println("=========promptValue======="+promptValue);
			
			
			add(1,new com.avaya.sce.runtime.PhraseVariableElement("Press:press" + i, com.avaya.sce.runtime.PhraseVariableElement.Type.AUDIO_URL, false));
			add(1,new com.avaya.sce.runtime.PhraseVariableElement("prompt:pm" + i, com.avaya.sce.runtime.PhraseVariableElement.Type.AUDIO_URL, false));
			
		}
	}
	
	
	
}
