package english.phrasesets;

/**
 * This phraseset class will be automatically populated with data from the 
 * phraseset project file.  Manual edits should only be outside of the tag 
 * areas or overridden methods. 
 * Class created on: 
 * Last generated by Orchestration Designer at: 2023-NOV-17  05:34:47 PM
 */
public class PhraseSet1 extends com.avaya.sce.runtime.Phraseset { 

	//{{START:CLASS:FIELDS
	private static final com.avaya.sce.runtime.Phraseset.PhraseMap PHRASE_MAP;
	//}}END:CLASS:FIELDS

	/**
	 * Static initializer
	 */
	static {
		//{{START:PHRASESET:STATIC

		// Create the phrase map, then populate with phrases
		PHRASE_MAP = new com.avaya.sce.runtime.Phraseset.PhraseMap(14);
		com.avaya.sce.runtime.Phrase phrase;

		// phrase: Welcome
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.PhraseSet1.urlbase", "Welcome", "Welcome.wav", ""); 

		// phrase: MAIN_MENU
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.PhraseSet1.urlbase", "MAIN_MENU", "MAIN_MENU.wav", ""); 

		// phrase: NINM_NOINPUT
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.PhraseSet1.urlbase", "NINM_NOINPUT", "NINM_NOINPUT.wav", ""); 

		// phrase: NINM_NOMATCH
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.PhraseSet1.urlbase", "NINM_NOMATCH", "NINM_NOMATCH.wav", ""); 

		// phrase: NINM_MAXTRY
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.PhraseSet1.urlbase", "NINM_MAXTRY", "NINM_MAXTRY.wav", ""); 

		// phrase: SALE_MENU
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.PhraseSet1.urlbase", "SALE_MENU", "SALE_MENU.wav", ""); 

		// phrase: SUPPORT_MENU
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.PhraseSet1.urlbase", "SUPPORT_MENU", "SUPPORT_MENU.wav", ""); 

		//}}END:PHRASESET:STATIC
	}
	/**
	 * Returns the Phrase with the given name.  To override the
	 * behavior and dynamically return a different Phrase object,
	 * override the method "hookGetPhrase(...)".
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2023-NOV-18  12:39:14 PM
	 * @see com.avaya.sce.runtime.Phraseset#getPhrase(String) 
	 */ 
	public com.avaya.sce.runtime.Phrase getPhrase(String phraseName) {
		return(getPhrase(PhraseSet1.PHRASE_MAP, phraseName));
	}
}
