package english.phrasesets;

/**
 * This phraseset class will be automatically populated with data from the 
 * phraseset project file.  Manual edits should only be outside of the tag 
 * areas or overridden methods. 
 * Class created on: 
 * Last generated by Orchestration Designer at: 2023-DEC-27  02:49:44 PM
 */
public class PhraseSet1 extends com.avaya.sce.runtime.Phraseset { 

	//{{START:CLASS:FIELDS
	private static final com.avaya.sce.runtime.Phraseset.PhraseMap PHRASE_MAP;
	//}}END:CLASS:FIELDS

	/**
	 * Static initializer
	 */
	static {
		//{{START:PHRASESET:STATIC

		// Create the phrase map, then populate with phrases
		PHRASE_MAP = new com.avaya.sce.runtime.Phraseset.PhraseMap(16);
		com.avaya.sce.runtime.Phrase phrase;

		// phrase: AT
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.PhraseSet1.urlbase", "AT", "AT.wav", ""); 

		// phrase: ListenAgain
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.PhraseSet1.urlbase", "ListenAgain", "ListenAgain.wav", ""); 

		// phrase: Thank
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.PhraseSet1.urlbase", "Thank", "Thank.wav", ""); 

		// phrase: TryAgain
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.PhraseSet1.urlbase", "TryAgain", "TryAgain.wav", ""); 

		// phrase: Otp
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.PhraseSet1.urlbase", "Otp", "Otp.wav", ""); 

		// phrase: ResendOtp
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.PhraseSet1.urlbase", "ResendOtp", "ResendOtp.wav", ""); 

		// phrase: AT1
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.PhraseSet1.urlbase", "AT1", "AT1.wav", ""); 

		// phrase: PinNotMatching
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.PhraseSet1.urlbase", "PinNotMatching", "PinNotMatching.wav", ""); 

		//}}END:PHRASESET:STATIC
	}
	/**
	 * Returns the Phrase with the given name.  To override the
	 * behavior and dynamically return a different Phrase object,
	 * override the method "hookGetPhrase(...)".
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2024-FEB-08  11:01:16 AM
	 * @see com.avaya.sce.runtime.Phraseset#getPhrase(String) 
	 */ 
	public com.avaya.sce.runtime.Phrase getPhrase(String phraseName) {
		return(getPhrase(PhraseSet1.PHRASE_MAP, phraseName));
	}
}
