package flow;

/**
 * This interface is used to define the name of variables that are 
 * declared in the call flow.  All variables are defined as 
 * <code>public static final String</code>, which allows user-defined
 * code to reference variable names by the Java variable name.
 * Last generated by Orchestration Designer at: 2023-NOV-20  01:43:55 PM
 */
public interface IProjectVariables {





	//{{START:PROJECT:VARIABLES
	/**
	 * This is a reserved block of variable name definitions.
	 * The variable names defined here can be used as the key
	 * to get the <code>com.avaya.sce.runtime.Variable</code>
	 * from the <code>SCESession</code> at runtime.<br>
	 * 
	 * For example, given a variable name <code>phoneNum</code>,
	 * user-defined code should access the variable in this format:<PRE>
	 *   Variable phNum = mySession.getVariable(IProjectVariables.PHONE_NUM);
	 *   if ( phNum != null ) {
	 *        // do something with the variable
	 *   }</PRE>
	 * 
	 * This block of code is generated automatically by Orchestration Designer and should not
	 * be manually edited as changes may be overwritten by future code generation.
	 * Last generated by Orchestration Designer at: 2023-NOV-27  01:23:29 PM
	 */
	public static final String DATE = "date";
	public static final String MENU_FOR_VALID = "MenuForValid";
	public static final String NICOUNT = "NICount";
	public static final String COUNT = "Count";
	public static final String NINM = "NINM";
	public static final String CUSTOM_TTNUM = "CustomTTNum";
	public static final String WS_1VARIABLES = "WS1Variables";
	public static final String REDIRECTINFO = "redirectinfo";
	public static final String SESSION = "session";
	public static final String DD_LAST_EXCEPTION = "ddLastException";
	public static final String MENU_FOR_NOT_VALID = "MenuForNotValid";
	public static final String PROPETY_VARIABLE = "PropetyVariable";
	public static final String TTFETCH = "TTFetch";
	public static final String TIME = "time";
	public static final String PROMPT = "prompt";
	public static final String SHAREDUUI = "shareduui";
	public static final String NMCOUNT = "NMCount";
	//}}END:PROJECT:VARIABLES
	//{{START:PROJECT:VARIABLEFIELDS
	public static final String DATE_FIELD_AUDIO = "audio";
	public static final String DATE_FIELD_DAYOFMONTH = "dayofmonth";
	public static final String DATE_FIELD_DAYOFWEEK = "dayofweek";
	public static final String DATE_FIELD_DAYOFWEEKNUM = "dayofweeknum";
	public static final String DATE_FIELD_DAYOFYEAR = "dayofyear";
	public static final String DATE_FIELD_MONTH = "month";
	public static final String DATE_FIELD_MONTHINYEAR = "monthinyear";
	public static final String DATE_FIELD_YEAR = "year";
	public static final String MENU_FOR_VALID_FIELD_CONFIDENCE = "confidence";
	public static final String MENU_FOR_VALID_FIELD_INPUTMODE = "inputmode";
	public static final String MENU_FOR_VALID_FIELD_INTERPRETATION = "interpretation";
	public static final String MENU_FOR_VALID_FIELD_NOINPUTCOUNT = "noinputcount";
	public static final String MENU_FOR_VALID_FIELD_NOMATCHCOUNT = "nomatchcount";
	public static final String MENU_FOR_VALID_FIELD_UTTERANCE = "utterance";
	public static final String MENU_FOR_VALID_FIELD_VALUE = "value";
	public static final String WS_1VARIABLES_FIELD_ID = "Id";
	public static final String WS_1VARIABLES_FIELD_LOGIN = "login";
	public static final String WS_1VARIABLES_FIELD_NAME = "name";
	public static final String REDIRECTINFO_FIELD_PRESENTATIONINFO = "presentationinfo";
	public static final String REDIRECTINFO_FIELD_REASON = "reason";
	public static final String REDIRECTINFO_FIELD_SCREENINGINFO = "screeninginfo";
	public static final String REDIRECTINFO_FIELD_URI = "uri";
	public static final String SESSION_FIELD_AAI = "aai";
	public static final String SESSION_FIELD_ANI = "ani";
	public static final String SESSION_FIELD_CALLTAG = "calltag";
	public static final String SESSION_FIELD_CHANNEL = "channel";
	public static final String SESSION_FIELD_CHANNELTYPE = "channeltype";
	public static final String SESSION_FIELD_CONVERSEFIRST = "conversefirst";
	public static final String SESSION_FIELD_CONVERSESECOND = "conversesecond";
	public static final String SESSION_FIELD_CURRENTLANGUAGE = "currentlanguage";
	public static final String SESSION_FIELD_DNIS = "dnis";
	public static final String SESSION_FIELD_EXIT_CUSTOMER_ID = "exitCustomerId";
	public static final String SESSION_FIELD_EXIT_INFO_1 = "exitInfo1";
	public static final String SESSION_FIELD_EXIT_INFO_2 = "exitInfo2";
	public static final String SESSION_FIELD_EXIT_PARENT_ID = "exitParentId";
	public static final String SESSION_FIELD_EXIT_PREFERRED_PATH = "exitPreferredPath";
	public static final String SESSION_FIELD_EXIT_REASON = "exitReason";
	public static final String SESSION_FIELD_EXIT_TOPIC = "exitTopic";
	public static final String SESSION_FIELD_LASTERROR = "lasterror";
	public static final String SESSION_FIELD_MEDIATYPE = "mediatype";
	public static final String SESSION_FIELD_PROTOCOLNAME = "protocolname";
	public static final String SESSION_FIELD_PROTOCOLVERSION = "protocolversion";
	public static final String SESSION_FIELD_SESSIONID = "sessionid";
	public static final String SESSION_FIELD_SESSIONLABEL = "sessionlabel";
	public static final String SESSION_FIELD_SHAREDMODE = "sharedmode";
	public static final String SESSION_FIELD_UCID = "ucid";
	public static final String SESSION_FIELD_UUI = "uui";
	public static final String SESSION_FIELD_VIDEOBITRATE = "videobitrate";
	public static final String SESSION_FIELD_VIDEOCODEC = "videocodec";
	public static final String SESSION_FIELD_VIDEOENABLED = "videoenabled";
	public static final String SESSION_FIELD_VIDEOFARFMTP = "videofarfmtp";
	public static final String SESSION_FIELD_VIDEOFORMAT = "videoformat";
	public static final String SESSION_FIELD_VIDEOFPS = "videofps";
	public static final String SESSION_FIELD_VIDEOHEIGHT = "videoheight";
	public static final String SESSION_FIELD_VIDEONEARFMTP = "videonearfmtp";
	public static final String SESSION_FIELD_VIDEOWIDTH = "videowidth";
	public static final String SESSION_FIELD_VPCALLEDEXTENSION = "vpcalledextension";
	public static final String SESSION_FIELD_VPCONVERSEONDATA = "vpconverseondata";
	public static final String SESSION_FIELD_VPCOVERAGEREASON = "vpcoveragereason";
	public static final String SESSION_FIELD_VPCOVERAGETYPE = "vpcoveragetype";
	public static final String SESSION_FIELD_VPRDNIS = "vprdnis";
	public static final String SESSION_FIELD_VPREPORTURL = "vpreporturl";
	public static final String DD_LAST_EXCEPTION_FIELD_ERRORCODE = "errorcode";
	public static final String DD_LAST_EXCEPTION_FIELD_MESSAGE = "message";
	public static final String DD_LAST_EXCEPTION_FIELD_OBJECT = "object";
	public static final String DD_LAST_EXCEPTION_FIELD_STACKTRACE = "stacktrace";
	public static final String DD_LAST_EXCEPTION_FIELD_TYPE = "type";
	public static final String MENU_FOR_NOT_VALID_FIELD_CONFIDENCE = "confidence";
	public static final String MENU_FOR_NOT_VALID_FIELD_INPUTMODE = "inputmode";
	public static final String MENU_FOR_NOT_VALID_FIELD_INTERPRETATION = "interpretation";
	public static final String MENU_FOR_NOT_VALID_FIELD_NOINPUTCOUNT = "noinputcount";
	public static final String MENU_FOR_NOT_VALID_FIELD_NOMATCHCOUNT = "nomatchcount";
	public static final String MENU_FOR_NOT_VALID_FIELD_UTTERANCE = "utterance";
	public static final String MENU_FOR_NOT_VALID_FIELD_VALUE = "value";
	public static final String PROPETY_VARIABLE_FIELD_NO_INPUT = "NoInput";
	public static final String PROPETY_VARIABLE_FIELD_NO_MATCH = "NoMatch";
	public static final String TTFETCH_FIELD_ID = "id";
	public static final String TTFETCH_FIELD_LOGIN = "login";
	public static final String TTFETCH_FIELD_NAME = "name";
	public static final String TTFETCH_FIELD_RESPONSE_CODE = "responseCode";
	public static final String TIME_FIELD_AUDIO = "audio";
	public static final String TIME_FIELD_HOUR = "hour";
	public static final String TIME_FIELD_MILLISECOND = "millisecond";
	public static final String TIME_FIELD_MINUTE = "minute";
	public static final String TIME_FIELD_SECOND = "second";
	public static final String TIME_FIELD_TIMEZONE = "timezone";
	public static final String PROMPT_FIELD_PM_0 = "pm0";
	public static final String PROMPT_FIELD_PM_1 = "pm1";
	public static final String PROMPT_FIELD_PM_2 = "pm2";
	public static final String PROMPT_FIELD_PM_3 = "pm3";
	public static final String PROMPT_FIELD_PM_4 = "pm4";
	public static final String SHAREDUUI_FIELD_ID = "id";
	public static final String SHAREDUUI_FIELD_VALUE = "value";
	//}}END:PROJECT:VARIABLEFIELDS
}
