package flow;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;

import com.avaya.sce.runtime.tracking.TraceInfo;
import com.avaya.sce.runtimecommon.ITraceInfo;
import com.avaya.sce.runtimecommon.SCESession;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.google.gson.Gson;

import okhttp3.MediaType;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;

/**
 * The Data class handles many types of server-side operations including data
 * collection (from a data sources such as a database, or web service), variable
 * assignments and operations (like copying variable values, performing mathematic
 * operations, and collection iteration), conditional evaluation to control callflow
 * execution based on variable values, and logging/tracing statements.
 * 
 * Items created in the getDataActions() method are executed/evaluated in order
 * and if a condional branch condition evaluates to "true" then the branch is
 * activated and the execution of data actions is halted.  If no "true" conditions
 * are encountered, then all data actions will be executed/evaluated and the 
 * application will proceed to the "Default" servlet.
 * Last generated by Orchestration Designer at: 2023-NOV-20  01:51:07 PM
 */
public class TTDetailsFetch extends com.avaya.sce.runtime.Data {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2023-NOV-20  01:51:07 PM
	 */
	public TTDetailsFetch() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * Returns the Next item which will forward application execution
	 * to the next form in the call flow.
	 * Last generated by Orchestration Designer at: 2023-NOV-24  07:02:24 PM
	 */
	public com.avaya.sce.runtime.Next getNext(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Next next = new com.avaya.sce.runtime.Next("QueryTTDetails", "QueryTT");
		next.setDebugId(6);
		return next;
	}
	
	
	/**
	 * Create a list of local variables used by items in the data node.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2023-NOV-24  07:02:24 PM
	 */
	public java.util.Collection<VariableInfo> getLocalVariables(){
		java.util.Collection<VariableInfo> variables = new java.util.ArrayList<VariableInfo>();

		return variables;
	}
	
	@Override
	public void requestBegin(SCESession mySession) {


//		OkHttpClient client = new OkHttpClient().newBuilder()
//				  .build();
//				MediaType mediaType = MediaType.parse("text/plain");
//				RequestBody body = RequestBody.create(mediaType, "");
//				Request request = new Request.Builder()
//				  .url("https://api.github.com/users/mojombo")
//				  .method("GET", null)
//				  .build();
//				try {
//					Response response = client.newCall(request).execute();
//					String resBody = response.body().toString();
//					
//					Gson gson = new Gson();
//					TestData testData = gson.fromJson(resBody, TestData.class);
//					int id = testData.getId();
		
//					System.out.println("===============id========= : "+id);					
//				    System.out.println("===============resBody========= : "+resBody);
		
//				} catch (IOException e) {
//					
//					e.printStackTrace();
//				}
		
		
		    URL url;
		try {
			url = new URL("https://api.github.com/users/mojombo");
		
	        HttpURLConnection connection = (HttpURLConnection) url.openConnection();
	        connection.setRequestMethod("GET");
	        
	        int responseCode = connection.getResponseCode();
	        
	        if (responseCode == HttpURLConnection.HTTP_OK) 
	          {
	            BufferedReader in = new BufferedReader(new InputStreamReader(connection.getInputStream()));
	            String inputLine;
	            StringBuilder response = new StringBuilder();

	            while ((inputLine = in.readLine()) != null) {
	                response.append(inputLine);
	            }
	            
	            String responseBody = response.toString();
	            
	            Gson gson = new Gson();
	           
				TestData testData = gson.fromJson(responseBody, TestData.class);
				int id = testData.getId();
				String name = testData.getName();
				String login = testData.getLogin();

	            TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"===============id========= : " + id, mySession);
	            TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"===============response========= : " + response, mySession);
	            TraceInfo.trace(ITraceInfo.TRACE_LEVEL_INFO,"===============responseCode========= : " + responseCode, mySession);
	            
	            mySession.getVariableField(IProjectVariables.TTFETCH, IProjectVariables.TTFETCH_FIELD_ID).setValue(id);
		        mySession.getVariableField(IProjectVariables.TTFETCH, IProjectVariables.TTFETCH_FIELD_LOGIN).setValue(login);
		        mySession.getVariableField(IProjectVariables.TTFETCH, IProjectVariables.TTFETCH_FIELD_NAME).setValue(name);
		        mySession.getVariableField(IProjectVariables.TTFETCH, IProjectVariables.TTFETCH_FIELD_RESPONSE_CODE).setValue(responseCode);
		        
	            in.close();
	            
	        } else {
	            throw new Exception("API request failed with response code: " + responseCode);
	        }
	        
		} catch (Exception e) {
			
			e.printStackTrace();
		}
		
	}
	/**
	 * Creates and conditionally executes operations that have been configured
	 * in the Callflow.  This method will build a collection of operations and
	 * have the framework execute the operations by calling evaluateActions().
	 * If the evaluation causes the framework to forward to a different servlet
	 * then execution stops.
	 * Returning true from this method means that the framework has forwarded the
	 * request to a different servlet.  Returning false means that the default
	 * Next will be invoked.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2023-NOV-24  07:02:24 PM
	 */
	public boolean executeDataActions(com.avaya.sce.runtimecommon.SCESession mySession) throws Exception {
		java.util.Collection actions = null;

		actions = new java.util.ArrayList(3);

		//{{START:CODEGEN:EXTENSIONPOINT:com.avaya.sce.restws.avResourceType
		actions.add(new connectivity.ws.operations.WS1(mySession).setDebugId(25));
		//}}END:CODEGEN:EXTENSIONPOINT:com.avaya.sce.restws.avResourceType

		actions.add(new com.avaya.sce.runtime.tracking.TraceInfo(com.avaya.sce.runtimecommon.ITraceInfo.TRACE_LEVEL_DEBUG, ">>>>TestId>>>>>>", "TTFetch:id").setDebugId(126));
		if(evaluateActions(actions, mySession)) {
			return true;
		}
		actions = null;

		// return false if the evaluation of actions did not cause a servlet forward or redirect
		return false;
	}
}
