package connectivity.db.operations;

/**
 * This class is generated automatically.  Manual edits must be outside of the tagged
 * areas (for example, "START:CLASS:..." and "END:CLASS:...").  Changes within the
 * tag areas will be overwritten when the database operation is regenerated.
 * Last generated by Orchestration Designer at: 2023-NOV-20  01:10:40 PM
 */
public class DbData extends com.avaya.sce.runtime.connectivity.db.DbQuery {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for DbData.
	 * Last generated by Orchestration Designer at: 2023-NOV-20  01:10:40 PM
	 */
	public DbData( com.avaya.sce.runtimecommon.IRuntimeSession mySession ) {
		//{{START:CLASS:CONSTRUCTOR
		super(mySession);

		setDataSourceName("jdbc/Db1");
		setDbObjectName("emp");
		setOperation(0);
		setReturnType(-1);
		setSQLQuery("SELECT emp.empId, emp.Name, emp.Email, emp.Phone FROM emp WHERE  ( emp.empId = ? )");

		// List variable that may be used
		java.util.List list;

		// Parameters
		com.avaya.sce.runtime.connectivity.db.DbQueryParam parameter;
		addParameter(new com.avaya.sce.runtime.connectivity.db.DbQueryParam("empId",0,4, "DbData:empId"));
		addParameter(new com.avaya.sce.runtime.connectivity.db.DbQueryParam("Name",0,12, "DbData:Name"));
		addParameter(new com.avaya.sce.runtime.connectivity.db.DbQueryParam("Email",0,12, "DbData:Email"));
		addParameter(new com.avaya.sce.runtime.connectivity.db.DbQueryParam("Phone",0,12, "DbData:Phone"));

		// Where parameters
		addWhereParameter(new com.avaya.sce.runtime.connectivity.db.DbQueryParam("empId",0,4,"PromptAndCollect1:value"));

		//}}END:CLASS:CONSTRUCTOR
	}

}

