package flow;

import java.util.HashMap;
import java.util.Map;

import com.avaya.sce.runtimecommon.SCESession;

/**
 * The Data class handles many types of server-side operations including data
 * collection (from a data sources such as a database, or web service), variable
 * assignments and operations (like copying variable values, performing mathematic
 * operations, and collection iteration), conditional evaluation to control callflow
 * execution based on variable values, and logging/tracing statements.
 * 
 * Items created in the getDataActions() method are executed/evaluated in order
 * and if a condional branch condition evaluates to "true" then the branch is
 * activated and the execution of data actions is halted.  If no "true" conditions
 * are encountered, then all data actions will be executed/evaluated and the 
 * application will proceed to the "Default" servlet.
 * Last generated by Orchestration Designer at: 2023-NOV-28  05:04:18 PM
 */
public class Data1 extends com.avaya.sce.runtime.Data {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2023-NOV-28  05:04:18 PM
	 */
	public Data1() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * Returns the Next item which will forward application execution
	 * to the next form in the call flow.
	 * Last generated by Orchestration Designer at: 2023-DEC-01  11:07:27 AM
	 */
	public com.avaya.sce.runtime.Next getNext(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Next next = null;
		return next;
	}
	/**
	 * Create a list of local variables used by items in the data node.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2023-DEC-01  11:07:27 AM
	 */
	public java.util.Collection<VariableInfo> getLocalVariables(){
		java.util.Collection<VariableInfo> variables = new java.util.ArrayList<VariableInfo>();

		return variables;
	}
	
	@Override
	public void requestBegin(SCESession mySession) {
		
		String menuValue = mySession.getVariableField(IProjectVariables.PROMPT_AND_COLLECT_1,IProjectVariables.PROMPT_AND_COLLECT_1_FIELD_VALUE).getStringValue();
		String[] grammars;
		String[] nextNodes;
		HashMap<String,String> keyandnode;
		
		 grammars = mySession.getVariableField(IProjectVariables.USER_STORE,IProjectVariables.USER_STORE_FIELD_GRAMMAR).getStringValue().trim().split(",");
		
		 nextNodes = mySession.getVariableField(IProjectVariables.USER_STORE,IProjectVariables.USER_STORE_FIELD_NEXT_NODE).getStringValue().trim().split(",");
		
		 try {
			 
			 keyandnode = new HashMap<String,String>();
			 
			 for(int i=0;i<grammars.length;i++) {
				 
				 keyandnode.put(grammars[i].trim(), nextNodes[i].trim());
			 }
			 
			 if(keyandnode.containsKey(menuValue)) {
				 String[] kn = (keyandnode.get(menuValue)).split(":");
				 
				 if(kn.length>1) {
					 
					 System.out.println( this.getName() +" >> "+ " >> Next Key :: " + kn[0] + " >> Next Node " + kn[1]);
					 mySession.getVariableField(IProjectVariables.USER_STORE, IProjectVariables.USER_STORE_FIELD_NEXT_NODE).setValue(kn[1]);
					 mySession.getVariableField(IProjectVariables.USER_STORE, IProjectVariables.USER_STORE_FIELD_NEXTKEYWORD).setValue(kn[0]);
					 
					 
				 }
				 else{
						mySession.getVariableField(IProjectVariables.USER_STORE, IProjectVariables.USER_STORE_FIELD_NEXT_NODE).setValue(kn[1]);
		
					}
			 }
			 
			 
		 }catch(Exception e)
		 {
			e.printStackTrace(); 
		 }
		
				
		
	}
	/**
	 * Creates and conditionally executes operations that have been configured
	 * in the Callflow.  This method will build a collection of operations and
	 * have the framework execute the operations by calling evaluateActions().
	 * If the evaluation causes the framework to forward to a different servlet
	 * then execution stops.
	 * Returning true from this method means that the framework has forwarded the
	 * request to a different servlet.  Returning false means that the default
	 * Next will be invoked.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2023-DEC-01  11:07:27 AM
	 */
	public boolean executeDataActions(com.avaya.sce.runtimecommon.SCESession mySession) throws Exception {
		java.util.Collection actions = null;

		actions = new java.util.ArrayList(1);
		if(evaluateActions(actions, mySession)) {
			return true;
		}
		actions = null;

		// switch start (104)
		if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition1", "UserStore:nextNode", com.avaya.sce.runtime.Expression.STRING_EQUAL, "Sale", false).setDebugId(104)).evaluate(mySession)) {
			actions = new java.util.ArrayList(1);
			actions.add(new com.avaya.sce.runtime.Next("Data2", "Sa").setDebugId(85));
			if(evaluateActions(actions, mySession)) {
				return true;
			}
			actions = null;

		} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition2", "UserStore:nextNode", com.avaya.sce.runtime.Expression.STRING_EQUAL, "Support", false).setDebugId(105)).evaluate(mySession)) {
			actions = new java.util.ArrayList(1);
			actions.add(new com.avaya.sce.runtime.Next("Data3", "Su").setDebugId(108));
			if(evaluateActions(actions, mySession)) {
				return true;
			}
			actions = null;

		} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition3", "UserStore:nextNode", com.avaya.sce.runtime.Expression.STRING_EQUAL, "Issue", false).setDebugId(106)).evaluate(mySession)) {
			actions = new java.util.ArrayList(1);
			actions.add(new com.avaya.sce.runtime.Next("Data4", "Iss").setDebugId(109));
			if(evaluateActions(actions, mySession)) {
				return true;
			}
			actions = null;

		} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition4", "UserStore:nextNode", com.avaya.sce.runtime.Expression.STRING_EQUAL, "Other", false).setDebugId(107)).evaluate(mySession)) {
			actions = new java.util.ArrayList(1);
			actions.add(new com.avaya.sce.runtime.Next("Data5", "Other").setDebugId(110));
			if(evaluateActions(actions, mySession)) {
				return true;
			}
			actions = null;

		}

		// return false if the evaluation of actions did not cause a servlet forward or redirect
		return false;
	}
}
