package flow;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

import com.avaya.sce.runtimecommon.SCESession;

/**
 * The Data class handles many types of server-side operations including data
 * collection (from a data sources such as a database, or web service), variable
 * assignments and operations (like copying variable values, performing mathematic
 * operations, and collection iteration), conditional evaluation to control callflow
 * execution based on variable values, and logging/tracing statements.
 * 
 * Items created in the getDataActions() method are executed/evaluated in order
 * and if a condional branch condition evaluates to "true" then the branch is
 * activated and the execution of data actions is halted.  If no "true" conditions
 * are encountered, then all data actions will be executed/evaluated and the 
 * application will proceed to the "Default" servlet.
 * Last generated by Orchestration Designer at: 2023-NOV-24  03:24:49 PM
 */
public class DeleteEmp extends com.avaya.sce.runtime.Data {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2023-NOV-24  03:24:49 PM
	 */
	public DeleteEmp() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * Returns the Next item which will forward application execution
	 * to the next form in the call flow.
	 * Last generated by Orchestration Designer at: 2023-NOV-28  07:03:29 PM
	 */
	public com.avaya.sce.runtime.Next getNext(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Next next = new com.avaya.sce.runtime.Next("Ann2", "Default");
		next.setDebugId(152);
		return next;
	}
	/**
	 * Create a list of local variables used by items in the data node.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2023-NOV-28  07:03:29 PM
	 */
	public java.util.Collection<VariableInfo> getLocalVariables(){
		java.util.Collection<VariableInfo> variables = new java.util.ArrayList<VariableInfo>();

		return variables;
	}
	@Override
	public void requestBegin(SCESession mySession) {
    String sessionId = mySession.getSessionId();
		
		LocalDateTime currentDateTime = LocalDateTime.now();
		DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
		String formattedDateTime = currentDateTime.format(formatter);

		mySession.getVariableField(IProjectVariables.SESSION_ID).setValue(sessionId);
		mySession.getVariableField(IProjectVariables.TIME_STAMP).setValue(formattedDateTime);
		mySession.getVariableField(IProjectVariables.USER_INPUTS,IProjectVariables.USER_INPUTS_FIELD_INPUT).setValue("Menu1:DeleteOption");
	}
	/**
	 * Creates and conditionally executes operations that have been configured
	 * in the Callflow.  This method will build a collection of operations and
	 * have the framework execute the operations by calling evaluateActions().
	 * If the evaluation causes the framework to forward to a different servlet
	 * then execution stops.
	 * Returning true from this method means that the framework has forwarded the
	 * request to a different servlet.  Returning false means that the default
	 * Next will be invoked.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2023-NOV-28  07:03:29 PM
	 */
	public boolean executeDataActions(com.avaya.sce.runtimecommon.SCESession mySession) throws Exception {
		java.util.Collection actions = null;

		actions = new java.util.ArrayList(3);

		//{{START:CODEGEN:EXTENSIONPOINT:com.avaya.sce.databaseoperations
		actions.add(new connectivity.db.operations.Del1(mySession).setDebugId(161));
		//}}END:CODEGEN:EXTENSIONPOINT:com.avaya.sce.databaseoperations


		//{{START:CODEGEN:EXTENSIONPOINT:com.avaya.sce.databaseoperations
		actions.add(new connectivity.db.operations.InsertLog(mySession).setDebugId(181));
		//}}END:CODEGEN:EXTENSIONPOINT:com.avaya.sce.databaseoperations

		if(evaluateActions(actions, mySession)) {
			return true;
		}
		actions = null;

		// return false if the evaluation of actions did not cause a servlet forward or redirect
		return false;
	}
}
