package english.phrasesets;

/**
 * This phraseset class will be automatically populated with data from the 
 * phraseset project file.  Manual edits should only be outside of the tag 
 * areas or overridden methods. 
 * Class created on: 
 * Last generated by Orchestration Designer at: 2023-NOV-21  12:43:11 PM
 */
public class TTOutbound1 extends com.avaya.sce.runtime.Phraseset { 

	//{{START:CLASS:FIELDS
	private static final com.avaya.sce.runtime.Phraseset.PhraseMap PHRASE_MAP;
	//}}END:CLASS:FIELDS

	/**
	 * Static initializer
	 */
	static {
		//{{START:PHRASESET:STATIC

		// Create the phrase map, then populate with phrases
		PHRASE_MAP = new com.avaya.sce.runtime.Phraseset.PhraseMap(58);
		com.avaya.sce.runtime.Phrase phrase;

		// phrase: ETOUTBOUND_001
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "ETOUTBOUND_001", "ETOUTBOUND_001.wav", ""); 

		// phrase: ETOUTBOUND_002
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "ETOUTBOUND_002", "ETOUTBOUND_002.wav", ""); 

		// phrase: ETOUTBOUND_003
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "ETOUTBOUND_003", "ETOUTBOUND_003.wav", ""); 

		// phrase: ETOUTBOUND_004
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "ETOUTBOUND_004", "ETOUTBOUND_004.wav", ""); 

		// phrase: ETOUTBOUND_005
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "ETOUTBOUND_005", "ETOUTBOUND_005.wav", ""); 

		// phrase: ETOUTBOUND_006
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "ETOUTBOUND_006", "ETOUTBOUND_006.wav", ""); 

		// phrase: ETOUTBOUND_007
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "ETOUTBOUND_007", "ETOUTBOUND_007.wav", ""); 

		// phrase: ETOUTBOUND_008
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "ETOUTBOUND_008", "ETOUTBOUND_008.wav", ""); 

		// phrase: ETOUTBOUND_009
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "ETOUTBOUND_009", "ETOUTBOUND_009.wav", ""); 

		// phrase: ETOUTBOUND_010
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "ETOUTBOUND_010", "ETOUTBOUND_010.wav", ""); 

		// phrase: ETOUTBOUND_011
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "ETOUTBOUND_011", "ETOUTBOUND_011.wav", ""); 

		// phrase: ETOUTBOUND_012
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "ETOUTBOUND_012", "ETOUTBOUND_012.wav", ""); 

		// phrase: ETOUTBOUND_013
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "ETOUTBOUND_013", "ETOUTBOUND_013.wav", ""); 

		// phrase: ETOUTBOUND_014
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "ETOUTBOUND_014", "ETOUTBOUND_014.wav", ""); 

		// phrase: ETOUTBOUND_015
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "ETOUTBOUND_015", "ETOUTBOUND_015.wav", ""); 

		// phrase: ETOUTBOUND_016
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "ETOUTBOUND_016", "ETOUTBOUND_016.wav", ""); 

		// phrase: ETOUTBOUND_017
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "ETOUTBOUND_017", "ETOUTBOUND_017.wav", ""); 

		// phrase: ETOUTBOUND_018
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "ETOUTBOUND_018", "ETOUTBOUND_018.wav", ""); 

		// phrase: ETOUTBOUND_019
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "ETOUTBOUND_019", "ETOUTBOUND_019.wav", ""); 

		// phrase: ETOUTBOUND_020
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "ETOUTBOUND_020", "ETOUTBOUND_020.wav", ""); 

		// phrase: ETOUTBOUND_033
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "ETOUTBOUND_033", "ETOUTBOUND_033.wav", ""); 

		// phrase: ETOUTBOUND_034
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "ETOUTBOUND_034", "ETOUTBOUND_034.wav", ""); 

		// phrase: ETOUTBOUND_035
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "ETOUTBOUND_035", "ETOUTBOUND_035.wav", ""); 

		// phrase: ETOUTBOUND_036
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "ETOUTBOUND_036", "ETOUTBOUND_036.wav", ""); 

		// phrase: ETOUTBOUND_037
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "ETOUTBOUND_037", "ETOUTBOUND_037.wav", ""); 

		// phrase: ETOUTBOUND_040
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "ETOUTBOUND_040", "ETOUTBOUND_040.wav", ""); 

		// phrase: ETOUTBOUND_041
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "ETOUTBOUND_041", "ETOUTBOUND_041.wav", ""); 

		// phrase: TTNotvalidMobile_02
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "TTNotvalidMobile_02", "TTNotvalidMobile_02.wav", ""); 

		// phrase: TTSolveMobile_01
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "TTSolveMobile_01", "TTSolveMobile_01.wav", ""); 

		//}}END:PHRASESET:STATIC
	}
	/**
	 * Returns the Phrase with the given name.  To override the
	 * behavior and dynamically return a different Phrase object,
	 * override the method "hookGetPhrase(...)".
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2023-NOV-24  07:02:24 PM
	 * @see com.avaya.sce.runtime.Phraseset#getPhrase(String) 
	 */ 
	public com.avaya.sce.runtime.Phrase getPhrase(String phraseName) {
		return(getPhrase(TTOutbound1.PHRASE_MAP, phraseName));
	}
}
