package connectivity.db.operations;

/**
 * This class is generated automatically.  Manual edits must be outside of the tagged
 * areas (for example, "START:CLASS:..." and "END:CLASS:...").  Changes within the
 * tag areas will be overwritten when the database operation is regenerated.
 * Last generated by Orchestration Designer at: 2023-NOV-23  03:48:15 PM
 */
public class Db1 extends com.avaya.sce.runtime.connectivity.db.DbQuery {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for Db1.
	 * Last generated by Orchestration Designer at: 2023-NOV-23  03:48:15 PM
	 */
	public Db1( com.avaya.sce.runtimecommon.IRuntimeSession mySession ) {
		//{{START:CLASS:CONSTRUCTOR
		super(mySession);

		setDataSourceName("jdbc/DbData");
		setDbObjectName("dbo.emp");
		setOperation(0);
		setReturnType(-1);
		setSQLQuery("SELECT emp.empId, emp.Name, emp.Email, emp.Phone FROM dbo.emp WHERE  ( emp.empId = ? )");

		// List variable that may be used
		java.util.List list;

		// Parameters
		com.avaya.sce.runtime.connectivity.db.DbQueryParam parameter;
		addParameter(new com.avaya.sce.runtime.connectivity.db.DbQueryParam("empId",0,4, "Db1:empId"));
		addParameter(new com.avaya.sce.runtime.connectivity.db.DbQueryParam("Name",0,12, "Db1:Name"));
		addParameter(new com.avaya.sce.runtime.connectivity.db.DbQueryParam("Email",0,12, "Db1:Email"));
		addParameter(new com.avaya.sce.runtime.connectivity.db.DbQueryParam("Phone",0,12, "Db1:Phone"));

		// Where parameters
		addWhereParameter(new com.avaya.sce.runtime.connectivity.db.DbQueryParam("empId",0,4,"EnterEmpId:value"));

		//}}END:CLASS:CONSTRUCTOR
	}

}

