package connectivity.db.operations;

/**
 * This class is generated automatically.  Manual edits must be outside of the tagged
 * areas (for example, "START:CLASS:..." and "END:CLASS:...").  Changes within the
 * tag areas will be overwritten when the database operation is regenerated.
 * Last generated by Orchestration Designer at: 2023-NOV-23  07:09:42 PM
 */
public class Del1 extends com.avaya.sce.runtime.connectivity.db.DbQuery {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for Del1.
	 * Last generated by Orchestration Designer at: 2023-NOV-23  07:09:42 PM
	 */
	public Del1( com.avaya.sce.runtimecommon.IRuntimeSession mySession ) {
		//{{START:CLASS:CONSTRUCTOR
		super(mySession);

		setDataSourceName("jdbc/DbData");
		setDbObjectName("dbo.emp");
		setOperation(2);
		setReturnType(-1);
		setSQLQuery("DELETE FROM dbo.emp WHERE  ( emp.empId = ? )");

		// Where parameters
		addWhereParameter(new com.avaya.sce.runtime.connectivity.db.DbQueryParam("empId",0,4,"EnterEmpId:value"));

		//}}END:CLASS:CONSTRUCTOR
	}

}

