package connectivity.db.operations;

/**
 * This class is generated automatically.  Manual edits must be outside of the tagged
 * areas (for example, "START:CLASS:..." and "END:CLASS:...").  Changes within the
 * tag areas will be overwritten when the database operation is regenerated.
 * Last generated by Orchestration Designer at: 2023-NOV-27  03:53:13 PM
 */
public class InsertLog extends com.avaya.sce.runtime.connectivity.db.DbQuery {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for InsertLog.
	 * Last generated by Orchestration Designer at: 2023-NOV-27  03:53:13 PM
	 */
	public InsertLog( com.avaya.sce.runtimecommon.IRuntimeSession mySession ) {
		//{{START:CLASS:CONSTRUCTOR
		super(mySession);

		setDataSourceName("jdbc/LogDb");
		setDbObjectName("dbo.logs");
		setOperation(3);
		setReturnType(-1);
		setSQLQuery("INSERT INTO dbo.logs ( sessionId, ani, dnis, time, input ) VALUES ( ?, ?, ?, ?, ? )");

		// List variable that may be used
		java.util.List list;

		// Parameters
		com.avaya.sce.runtime.connectivity.db.DbQueryParam parameter;
		addParameter(new com.avaya.sce.runtime.connectivity.db.DbQueryParam("sessionId",0,12, "sessionId"));
		addParameter(new com.avaya.sce.runtime.connectivity.db.DbQueryParam("ani",0,12, "aniTest"));
		addParameter(new com.avaya.sce.runtime.connectivity.db.DbQueryParam("dnis",0,12, "dnisTest"));
		addParameter(new com.avaya.sce.runtime.connectivity.db.DbQueryParam("time",0,93, "timeStamp"));
		addParameter(new com.avaya.sce.runtime.connectivity.db.DbQueryParam("input",0,12, "UserInputs:input"));

		//}}END:CLASS:CONSTRUCTOR
	}

}

