package english.grammars;

/**
 * This class is generated automatically.
 * Only exit this class for Dynamic External grammars and override the method String getURL().
 * Last generated by Orchestration Designer at: 2023-NOV-28  03:26:38 PM
 */
public class Gm1 extends com.avaya.sce.runtime.Grammar {

    //{{START:CLASS:FIELDS
    //}}END:CLASS:FIELDS

    /**
    * Constructor for Gm1.
    */
    public Gm1() {
		//{{START:CLASS:CONSTRUCTOR
        super();
        setRootLanguage("en-us");
        setMode("voice");
        setBuiltin(true);
        setBuiltinMode("grammar");
        setType("digits");
        setOptions("length=1");
		//}}END:CLASS:CONSTRUCTOR
    }

}

